-- Create roles table for role-based access control
CREATE TABLE IF NOT EXISTS roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '{}',
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default roles
INSERT INTO roles (name, description, permissions, is_default) VALUES
(
  'Admin Team',
  'Full access to all areas of the admin dashboard',
  '{
    "master_panel": true,
    "crm": true,
    "contacts": true,
    "projects": true,
    "proposals": true,
    "contracts": true,
    "invoices": true,
    "finances": true,
    "page_editor": true,
    "case_studies": true,
    "speakers": true,
    "analytics": true,
    "workshops": true,
    "newsletter": true,
    "blog": true,
    "vendor_directory": true,
    "landing_resources": true,
    "whatsapp": true,
    "system": true,
    "settings": true
  }',
  TRUE
),
(
  'Sales Team',
  'Access to CRM, contacts, proposals, and contracts',
  '{
    "master_panel": true,
    "crm": true,
    "contacts": true,
    "proposals": true,
    "contracts": true,
    "invoices": false,
    "finances": false,
    "projects": false,
    "page_editor": false,
    "case_studies": false,
    "speakers": true,
    "analytics": false,
    "workshops": false,
    "newsletter": false,
    "blog": false,
    "vendor_directory": false,
    "landing_resources": false,
    "whatsapp": false,
    "system": false,
    "settings": false
  }',
  FALSE
),
(
  'Web Developer',
  'Access to website management and technical tools',
  '{
    "master_panel": true,
    "crm": false,
    "contacts": false,
    "proposals": false,
    "contracts": false,
    "invoices": false,
    "finances": false,
    "projects": false,
    "page_editor": true,
    "case_studies": true,
    "speakers": true,
    "analytics": true,
    "workshops": true,
    "newsletter": false,
    "blog": true,
    "vendor_directory": true,
    "landing_resources": true,
    "whatsapp": false,
    "system": true,
    "settings": false
  }',
  FALSE
),
(
  'Operations',
  'Access to project management, contracts, and invoicing',
  '{
    "master_panel": true,
    "crm": false,
    "contacts": true,
    "proposals": true,
    "contracts": true,
    "invoices": true,
    "finances": true,
    "projects": true,
    "page_editor": false,
    "case_studies": false,
    "speakers": true,
    "analytics": false,
    "workshops": true,
    "newsletter": false,
    "blog": false,
    "vendor_directory": true,
    "landing_resources": false,
    "whatsapp": false,
    "system": false,
    "settings": false
  }',
  FALSE
),
(
  'Speaker Relations',
  'Access to speaker management and related content',
  '{
    "master_panel": true,
    "crm": false,
    "contacts": true,
    "proposals": true,
    "contracts": true,
    "invoices": false,
    "finances": false,
    "projects": true,
    "page_editor": false,
    "case_studies": true,
    "speakers": true,
    "analytics": false,
    "workshops": true,
    "newsletter": false,
    "blog": false,
    "vendor_directory": false,
    "landing_resources": false,
    "whatsapp": false,
    "system": false,
    "settings": false
  }',
  FALSE
),
(
  'Marketing',
  'Access to marketing tools, content, and analytics',
  '{
    "master_panel": true,
    "crm": false,
    "contacts": false,
    "proposals": false,
    "contracts": false,
    "invoices": false,
    "finances": false,
    "projects": false,
    "page_editor": false,
    "case_studies": true,
    "speakers": true,
    "analytics": true,
    "workshops": false,
    "newsletter": true,
    "blog": true,
    "vendor_directory": true,
    "landing_resources": true,
    "whatsapp": true,
    "system": false,
    "settings": false
  }',
  FALSE
),
(
  'Accountant',
  'Access to financial data, invoices, and contracts',
  '{
    "master_panel": true,
    "crm": false,
    "contacts": false,
    "proposals": false,
    "contracts": true,
    "invoices": true,
    "finances": true,
    "projects": false,
    "page_editor": false,
    "case_studies": false,
    "speakers": false,
    "analytics": false,
    "workshops": false,
    "newsletter": false,
    "blog": false,
    "vendor_directory": false,
    "landing_resources": false,
    "whatsapp": false,
    "system": false,
    "settings": false
  }',
  FALSE
)
ON CONFLICT (name) DO NOTHING;
